import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

/**
 * Writes dist/_headers for Cloudflare Pages.
 *
 * Astro emits a few inline scripts per page: its island runtime, plus the small
 * behaviours in Shell and Legal. Rather than opening the policy with
 * 'unsafe-inline', every inline script is hashed here and named in the policy,
 * so anything injected later has no way in. The hashes are regenerated on every
 * build, which is exactly why this runs as part of it.
 */

const DIST = 'dist';
const TURNSTILE = 'https://challenges.cloudflare.com';
const FONTS_CSS = 'https://fonts.googleapis.com';
const FONTS_FILES = 'https://fonts.gstatic.com';

async function htmlFiles(dir) {
  const found = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) found.push(...(await htmlFiles(path)));
    else if (entry.name.endsWith('.html')) found.push(path);
  }
  return found;
}

function inlineScripts(html) {
  const bodies = [];
  const pattern = /<script([^>]*)>([\s\S]*?)<\/script>/g;
  let match;
  while ((match = pattern.exec(html)) !== null) {
    const [, attributes, body] = match;
    if (/\ssrc=/.test(attributes)) continue;
    if (body.length) bodies.push(body);
  }
  return bodies;
}

const hashes = new Set();
for (const file of await htmlFiles(DIST)) {
  for (const body of inlineScripts(await readFile(file, 'utf8'))) {
    hashes.add(`'sha256-${createHash('sha256').update(body, 'utf8').digest('base64')}'`);
  }
}

const csp = [
  "default-src 'self'",
  "base-uri 'self'",
  "object-src 'none'",
  "frame-ancestors 'none'",
  "form-action 'self'",
  // Media previews are object URLs, which is why blob: is here. Nothing is
  // fetched from a third party.
  "img-src 'self' data: blob:",
  "media-src 'self' blob:",
  `font-src 'self' ${FONTS_FILES}`,
  // The design carries its measurements in style attributes, so inline styles
  // cannot be avoided. Script injection is the risk this policy is about.
  `style-src 'self' 'unsafe-inline' ${FONTS_CSS}`,
  `script-src 'self' ${TURNSTILE} ${[...hashes].sort().join(' ')}`,
  `frame-src ${TURNSTILE}`,
  `connect-src 'self' ${TURNSTILE}`,
  'upgrade-insecure-requests',
].join('; ');

const headers = `# Generated by scripts/build-headers.mjs. Do not edit dist directly.
/*
  Content-Security-Policy: ${csp}
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: accelerometer=(), camera=(), geolocation=(), gyroscope=(), microphone=(), payment=(), usb=()
  Cross-Origin-Opener-Policy: same-origin
  Cross-Origin-Resource-Policy: same-origin

# Fingerprinted assets never change under the same name.
/_astro/*
  Cache-Control: public, max-age=31536000, immutable

/icons/*
  Cache-Control: public, max-age=604800

/favicon.svg
  Cache-Control: public, max-age=604800

/logo.png
  Cache-Control: public, max-age=604800

/og.png
  Cache-Control: public, max-age=604800

/api/*
  Cache-Control: no-store
`;

await writeFile(join(DIST, '_headers'), headers, 'utf8');
console.log(`_headers written with ${hashes.size} inline script hashes`);
